---
abstract: unknown
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.59
  version: 0.77
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: carton
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Carton:
    file: lib/Carton.pm
    version: v0.9_8
  Carton::CLI:
    file: lib/Carton/CLI.pm
    version: 0
  Carton::Error:
    file: lib/Carton/Error.pm
    version: 0
  Carton::Tree:
    file: lib/Carton/Tree.pm
    version: 0
  Carton::TreeNode:
    file: lib/Carton/Tree.pm
    version: 0
  Carton::Util:
    file: lib/Carton/Util.pm
    version: 0
requires:
  App::cpanminus: 1.502
  CPAN::Meta: 2.120921
  CPAN::Meta::Requirements: 2.121
  Capture::Tiny: 0
  Exception::Class: 1.32
  ExtUtils::MakeMaker: 6.59
  Getopt::Long: 2.36
  IO::Compress::Gzip: 0
  JSON: 2.53
  Module::Build: 0.38
  Module::CPANfile: 0.9004
  Module::Metadata: 1.000003
  Term::ANSIColor: 1.12
  Try::Tiny: 0.09
  local::lib: 1.008
  parent: 0.223
  perl: v5.8.1
resources:
  bugtracker: https://github.com/miyagawa/carton/issues
  homepage: https://github.com/miyagawa/carton
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/carton.git
version: v0.9_8
