---
abstract: 'Perl module dependency manager (aka Bundler for Perl)'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
  version: 0.77
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: carton
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  App::cpanminus: 1.6915
  CPAN::Meta: 2.120921
  CPAN::Meta::Requirements: 2.121
  Exception::Class: 1.32
  ExtUtils::MakeMaker: 6.59
  Getopt::Long: 2.39
  JSON: 2.53
  Module::Build: 0.38
  Module::CPANfile: 0.9031
  Module::Metadata: 1.000003
  Moo: 1.002
  Path::Tiny: 0.022
  Try::Tiny: 0.09
  local::lib: 1.008
  parent: 0.223
  perl: v5.8.5
resources:
  bugtracker: https://github.com/miyagawa/carton/issues
  homepage: https://github.com/miyagawa/carton
  repository: https://github.com/miyagawa/carton.git
version: v0.9.57
x_contributors:
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'David Golden <dagolden@cpan.org>'
  - 'Masahiro Chiba <chiba@everqueue.com>'
  - 'NAKAGAWA Masaki <masaki.nakagawa@gmail.com>'
  - 'Pedro Figueiredo <me@pedrofigueiredo.org>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
  - 'ikasam_a <masaki.nakagawa@gmail.com>'
